version: "3.9"
services:
    backend:
        image: spring-boot
        container_name: sprint-boot
        build:
            context: ./spring-boot
        ports:
            - "8080:80"
    frontend:
        image: angular
        container_name: angular
        build:
            context: ./angular
        ports:
            - "8000:80"
        depends_on:
            - backend   